import type { Field } from "../types.js";

/** Primary key used everywhere: uuid, generated by Directus. */
export const pk = (): Field => ({
  field: "id",
  type: "uuid",
  meta: { hidden: true, readonly: true, interface: "input", special: ["uuid"] },
  schema: { is_primary_key: true, has_auto_increment: false },
});

/**
 * Every clinical and billing collection carries `clinic`. Multi-tenancy in
 * Directus is a row filter, not a separate database — every policy scopes
 * reads to `clinic = $CURRENT_USER.clinic`, so one instance safely serves
 * many practices. Getting this field on every collection is what makes
 * that possible; miss one and you have a data leak.
 */
export const clinicRef = (): Field => ({
  field: "clinic",
  type: "uuid",
  meta: {
    interface: "select-dropdown-m2o",
    special: ["m2o"],
    required: true,
    note: "$t:enamel_note_clinic",
    options: { template: "{{name}}" },
    width: "half",
  },
  schema: { is_nullable: false },
});

export const timestamps = (): Field[] => [
  {
    field: "date_created",
    type: "timestamp",
    meta: {
      special: ["date-created"], interface: "datetime", readonly: true,
      hidden: true, width: "half",
    },
    schema: {},
  },
  {
    field: "user_created",
    type: "uuid",
    meta: {
      special: ["user-created"], interface: "select-dropdown-m2o", readonly: true,
      hidden: true, width: "half", options: { template: "{{first_name}} {{last_name}}" },
    },
    schema: {},
  },
  {
    field: "date_updated",
    type: "timestamp",
    meta: {
      special: ["date-updated"], interface: "datetime", readonly: true,
      hidden: true, width: "half",
    },
    schema: {},
  },
  {
    field: "user_updated",
    type: "uuid",
    meta: {
      special: ["user-updated"], interface: "select-dropdown-m2o", readonly: true,
      hidden: true, width: "half", options: { template: "{{first_name}} {{last_name}}" },
    },
    schema: {},
  },
];

export const status = (
  choices: Array<{ text: string; value: string; color?: string }>,
  defaultValue: string,
): Field => ({
  field: "status",
  type: "string",
  meta: {
    interface: "select-dropdown",
    display: "labels",
    display_options: { showAsDot: true, choices },
    options: { choices },
    width: "half",
  },
  schema: { default_value: defaultValue, is_nullable: false },
});

export const divider = (title: string, key: string, icon = "info"): Field => ({
  field: key,
  type: "alias",
  meta: {
    interface: "presentation-divider",
    special: ["alias", "no-data"],
    options: { title, icon },
  },
  schema: null,
});

/**
 * FDI two-digit notation is not a contiguous range: 19, 20, 29, 30 and
 * so on do not exist. An `_in` list of the real numbers rejects them,
 * where a `_between 11 and 48` would quietly accept nonsense.
 */
export const ADULT_FDI = [
  11, 12, 13, 14, 15, 16, 17, 18, 21, 22, 23, 24, 25, 26, 27, 28,
  31, 32, 33, 34, 35, 36, 37, 38, 41, 42, 43, 44, 45, 46, 47, 48,
];
export const DECIDUOUS_FDI = [
  51, 52, 53, 54, 55, 61, 62, 63, 64, 65,
  71, 72, 73, 74, 75, 81, 82, 83, 84, 85,
];
export const ALL_FDI = [...ADULT_FDI, ...DECIDUOUS_FDI];

/** Attaches a validation filter and the message shown when it fails. */
export function validated(
  field: Field,
  validation: Record<string, unknown>,
  message: string,
): Field {
  return {
    ...field,
    meta: { ...(field.meta ?? {}), validation, validation_message: message },
  };
}

/** Loose but useful: catches typos without rejecting valid odd addresses. */
export const EMAIL_RE = "^[^@\\s]+@[^@\\s]+\\.[^@\\s]{2,}$";

/**
 * Templates for the m2o fields that do not carry one on the interface.
 * Keyed by field name, because `patient` means the same thing on every
 * collection it appears on.
 */
const RELATED_TEMPLATES: Record<string, string> = {
  clinic: "{{name}}",
  patient: "{{last_name}}, {{first_name}}",
  practitioner: "{{first_name}} {{last_name}}",
  portal_user: "{{first_name}} {{last_name}}",
  user_created: "{{first_name}} {{last_name}}",
  user_updated: "{{first_name}} {{last_name}}",
  room: "{{name}}",
  treatment: "{{code}} — {{name}}",
  appointment: "{{starts_at}}",
  treatment_record: "{{performed_at}}",
  invoice: "{{number}}",
};

/**
 * Gives every m2o a display as well as an interface.
 *
 * `interface` decides what the *form* shows; `display` decides what a
 * list, a bookmark column or a related-values chip shows. Set one and
 * not the other — which is the easy mistake, because the form looks
 * right — and every table in the admin renders a raw uuid where a name
 * should be. It is the first thing anyone notices and the last thing
 * anyone thinks to configure.
 *
 * Applied centrally rather than field by field: there are seventeen of
 * them, and the eighteenth would have been forgotten.
 */
export function withRelatedDisplay(field: Field): Field {
  const meta = field.meta as Record<string, unknown> | undefined;
  if (!meta) return field;
  const special = meta["special"];
  const isM2O = Array.isArray(special) && special.includes("m2o");
  if (!isM2O || meta["display"]) return field;

  const options = (meta["options"] ?? {}) as { template?: string };
  const template = options.template ?? RELATED_TEMPLATES[field.field];
  if (!template) return field;

  return {
    ...field,
    meta: { ...meta, display: "related-values", display_options: { template } },
  };
}
