import type { Field } from "../types.js";

/** Primary key used everywhere: uuid, generated by Directus. */
export const pk = (): Field => ({
  field: "id",
  type: "uuid",
  meta: { hidden: true, readonly: true, interface: "input", special: ["uuid"] },
  schema: { is_primary_key: true, has_auto_increment: false },
});

/**
 * Every clinical and billing collection carries `clinic`. Multi-tenancy in
 * Directus is a row filter, not a separate database — every policy scopes
 * reads to `clinic = $CURRENT_USER.clinic`, so one instance safely serves
 * many practices. Getting this field on every collection is what makes
 * that possible; miss one and you have a data leak.
 */
export const clinicRef = (): Field => ({
  field: "clinic",
  type: "uuid",
  meta: {
    interface: "select-dropdown-m2o",
    special: ["m2o"],
    required: true,
    note: "$t:enamel_note_clinic",
    options: { template: "{{name}}" },
    width: "half",
  },
  schema: { is_nullable: false },
});

export const timestamps = (): Field[] => [
  {
    field: "date_created",
    type: "timestamp",
    meta: {
      special: ["date-created"], interface: "datetime", readonly: true,
      hidden: true, width: "half",
    },
    schema: {},
  },
  {
    field: "user_created",
    type: "uuid",
    meta: {
      special: ["user-created"], interface: "select-dropdown-m2o", readonly: true,
      hidden: true, width: "half", options: { template: "{{first_name}} {{last_name}}" },
    },
    schema: {},
  },
  {
    field: "date_updated",
    type: "timestamp",
    meta: {
      special: ["date-updated"], interface: "datetime", readonly: true,
      hidden: true, width: "half",
    },
    schema: {},
  },
  {
    field: "user_updated",
    type: "uuid",
    meta: {
      special: ["user-updated"], interface: "select-dropdown-m2o", readonly: true,
      hidden: true, width: "half", options: { template: "{{first_name}} {{last_name}}" },
    },
    schema: {},
  },
];

export const status = (
  choices: Array<{ text: string; value: string; color?: string }>,
  defaultValue: string,
): Field => ({
  field: "status",
  type: "string",
  meta: {
    interface: "select-dropdown",
    display: "labels",
    /**
     * The dot stays here and nowhere else. `status()` is the two-value
     * archive switch — active or archived, live or void — where the
     * colour is the whole message and a word beside it is noise.
     *
     * A dot on a set of three or eight is a different thing: nobody can
     * tell caries from a crown, or agreed from disagreed, by hue. Those
     * fields render their label.
     */
    display_options: { showAsDot: true, choices },
    options: { choices },
    width: "half",
  },
  schema: { default_value: defaultValue, is_nullable: false },
});

export const divider = (title: string, key: string, icon = "info"): Field => ({
  field: key,
  type: "alias",
  meta: {
    interface: "presentation-divider",
    special: ["alias", "no-data"],
    options: { title, icon },
  },
  schema: null,
});

/**
 * Tooth designations.
 *
 * Two standards, and they are deliberately separate. That separation is
 * the reason this is a `string` column and not the integer it used to be.
 *
 * **ISO 3950:2009 / FDI two-digit** covers the teeth a mouth is supposed
 * to have, and nothing else. First digit is the quadrant — 1–4 permanent,
 * clockwise from the upper right; 5–8 deciduous. Second digit is the
 * tooth, 1–8 permanent (central incisor to third molar) and 1–5
 * deciduous. That is exactly 52 valid codes and not a contiguous range:
 * 19, 20, 29 and 30 do not exist, so an `_in` list rejects them where a
 * `_between 11 and 48` would quietly accept nonsense.
 *
 * **ISO 10394:2023** covers supernumerary teeth, and exists precisely
 * because ISO 3950 cannot be stretched to hold them. From its
 * introduction: "ISO 3950 has assigned a meaning to most of the available
 * combinations of two digits. As a result, ISO 3950 cannot be [expanded]
 * to satisfactorily identify supernumerary teeth without introducing
 * significant changes to its structure." One of its stated design
 * requirements is that it "does not assign a new meaning to designations
 * that exist in ISO 3950" — so any scheme that recycles two-digit codes
 * for extra teeth (19, 29, 2.9) is contrary to the committee's explicit
 * intent, however often you see it in the wild.
 *
 * Letters instead: A1–A8 upper right, B1–B8 upper left, C1–C8 lower left,
 * D1–D8 lower right, following the same clockwise sweep as ISO 3950's
 * quadrants. Plus two midline codes — AB in the maxilla, DC in the
 * mandible. `DC`, not `CD`: the two letters flanking each midline are read
 * in arch order, and normalising it would be wrong.
 *
 * A mesiodens — the commonest supernumerary in the permanent dentition,
 * sitting between the upper central incisors — is `AB`. Not 11, not 21,
 * not a flag on tooth 11.
 */
export const PERMANENT_FDI = [
  "11", "12", "13", "14", "15", "16", "17", "18",
  "21", "22", "23", "24", "25", "26", "27", "28",
  "31", "32", "33", "34", "35", "36", "37", "38",
  "41", "42", "43", "44", "45", "46", "47", "48",
];
export const DECIDUOUS_FDI = [
  "51", "52", "53", "54", "55", "61", "62", "63", "64", "65",
  "71", "72", "73", "74", "75", "81", "82", "83", "84", "85",
];

/**
 * ISO 10394:2023 supernumerary designations. 34 of them: eight per
 * quadrant, plus the two midline codes.
 *
 * Note what this standard refuses to do, because both refusals shape the
 * schema. It "does not classify supernumerary teeth as deciduous or
 * permanent", so there is one code set spanning both dentitions rather
 * than the 1–4/5–8 split ISO 3950 uses. And "when multiple supernumerary
 * teeth are present in the same location, the same code is used for the
 * designation of each of those supernumerary teeth" — so a designation is
 * NOT unique per tooth. A double mesiodens is two teeth both called AB,
 * which happens in roughly one in six mesiodens patients, so a
 * `UNIQUE (patient, designation)` constraint would reject valid records.
 */
export const SUPERNUMERARY_ISO10394 = [
  ...["A", "B", "C", "D"].flatMap((q) => [1, 2, 3, 4, 5, 6, 7, 8].map((n) => `${q}${n}`)),
  "AB",
  "DC",
];

/** Every designation this instance will accept: 52 + 34 = 86. */
export const ALL_TOOTH_CODES = [
  ...PERMANENT_FDI,
  ...DECIDUOUS_FDI,
  ...SUPERNUMERARY_ISO10394,
];

/**
 * A designation alone is ambiguous across notations, which is why every
 * tooth reference here is documented as ISO rather than left to a
 * reader's assumption. The US Universal system numbers supernumerary
 * permanent teeth 51–82 — the same integers ISO 3950 uses for deciduous
 * teeth. "51" is an upper-right deciduous central incisor in one system
 * and a supernumerary behind tooth 1 in the other, and nothing in the
 * value says which.
 */
export const TOOTH_CODE_MESSAGE = "$t:enamel_vm_tooth_code";

/** Attaches a validation filter and the message shown when it fails. */
export function validated(
  field: Field,
  validation: Record<string, unknown>,
  message: string,
): Field {
  return {
    ...field,
    meta: { ...(field.meta ?? {}), validation, validation_message: message },
  };
}

/** Loose but useful: catches typos without rejecting valid odd addresses. */
export const EMAIL_RE = "^[^@\\s]+@[^@\\s]+\\.[^@\\s]{2,}$";

/**
 * Templates for the m2o fields that do not carry one on the interface.
 * Keyed by field name, because `patient` means the same thing on every
 * collection it appears on.
 */
const RELATED_TEMPLATES: Record<string, string> = {
  clinic: "{{name}}",
  patient: "{{last_name}}, {{first_name}}",
  practitioner: "{{first_name}} {{last_name}}",
  portal_user: "{{first_name}} {{last_name}}",
  user_created: "{{first_name}} {{last_name}}",
  user_updated: "{{first_name}} {{last_name}}",
  room: "{{name}}",
  treatment: "{{code}} — {{name}}",
  appointment: "{{starts_at}}",
  treatment_record: "{{performed_at}}",
  invoice: "{{number}}",
};

/**
 * Gives every m2o a display as well as an interface.
 *
 * `interface` decides what the *form* shows; `display` decides what a
 * list, a bookmark column or a related-values chip shows. Set one and
 * not the other — which is the easy mistake, because the form looks
 * right — and every table in the admin renders a raw uuid where a name
 * should be. It is the first thing anyone notices and the last thing
 * anyone thinks to configure.
 *
 * Applied centrally rather than field by field: there are seventeen of
 * them, and the eighteenth would have been forgotten.
 */
export function withRelatedDisplay(field: Field): Field {
  const meta = field.meta as Record<string, unknown> | undefined;
  if (!meta) return field;
  const special = meta["special"];
  const isM2O = Array.isArray(special) && special.includes("m2o");
  if (!isM2O || meta["display"]) return field;

  const options = (meta["options"] ?? {}) as { template?: string };
  const template = options.template ?? RELATED_TEMPLATES[field.field];
  if (!template) return field;

  return {
    ...field,
    meta: { ...meta, display: "related-values", display_options: { template } },
  };
}

/**
 * Gives every dropdown a display as well as an interface.
 *
 * The same trap as `withRelatedDisplay`, one field type over: a
 * `select-dropdown` with no `display` renders its raw *value* in a list.
 * So `tooth_conditions.surface` showed "whole" instead of "Whole tooth",
 * and — worse, since sixty labels were just translated — a Dutch user got
 * "whole" where the form beside it says "Hele tand". Thirty-one fields
 * were like that.
 *
 * `labels` reuses the interface's own choices, so a label and its
 * translation are defined once. No `showAsDot`: a dot is right where the
 * colour carries the meaning, and these are words.
 */
export function withChoiceDisplay(field: Field): Field {
  const meta = field.meta as Record<string, unknown> | undefined;
  if (!meta || meta["interface"] !== "select-dropdown") return field;
  const options = (meta["options"] ?? {}) as { choices?: unknown };
  if (!Array.isArray(options.choices) || options.choices.length === 0) return field;

  const display = meta["display"];
  const displayOptions = (meta["display_options"] ?? {}) as Record<string, unknown>;

  // Nothing declared: give it the labels display and the interface's own
  // choices.
  if (!display) {
    return {
      ...field,
      meta: { ...meta, display: "labels", display_options: { ...displayOptions, choices: options.choices } },
    };
  }

  // Declared `labels` but no choices to map with — which renders an empty
  // cell, or a bare dot if showAsDot is set. This was the `condition`
  // column: eight distinct findings and nothing on screen for any of
  // them. Fill the choices in and leave everything else as declared.
  if (display === "labels" && !Array.isArray(displayOptions["choices"])) {
    return {
      ...field,
      meta: { ...meta, display_options: { ...displayOptions, choices: options.choices } },
    };
  }

  return field;
}
